apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: ddd
spec:
  replicas: 2  # number of pod replicas you want
  selector:
    matchLabels:
      app: ddd
  template:
    metadata:
      labels:
        app: ddd
    spec:
      containers:
      - name: my-app-container
        image: ddd:1.0.0 # The image built by Jenkins (should exist in Minikube's Docker daemon)
        ports:
        - containerPort: 5000  # Or your app's exposed port
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: ddd
  ports:
    - protocol: TCP
      port: 80            # Cluster IP service port
      targetPort: 8000    # The port your app container exposes
  type: NodePort   # Or ClusterIP / LoadBalancer based on your need
