pipeline {
    agent any
    environment {
        DOCKER_TLS_VERIFY = "1"
        DOCKER_HOST = "tcp://192.168.58.2:2376"
        DOCKER_CERT_PATH = "/var/lib/jenkins/.minikube/certs"
        MINIKUBE_ACTIVE_DOCKERD = "minikube"
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
        KUBECTL_PATH = "/var/lib/docker/volumes/minikube/_data/lib/minikube/binaries/v1.32.0/kubectl"
    }
    stages {
        stage('Build and Deploy') {
            steps {
                dir('Model_Api') {
                    sh '''
                        # Set Docker env for Minikube
                        eval $(minikube docker-env)

                        # Check Docker connection
                        docker version

                        # Build Docker image
                        docker build -t ddd:1.0.0 .

                        # Check kubectl version for sanity
                        ${KUBECTL_PATH} version --client

                        # Apply Kubernetes deployment and service configs
                        ${KUBECTL_PATH} apply -f deployment.yaml
                        ${KUBECTL_PATH} apply -f service.yaml
                    '''
                }
            }
        }
    }
}
