pipeline {
    agent any
    environment {
        DOCKER_TLS_VERIFY = "1"
        DOCKER_HOST = "tcp://192.168.58.2:2376" // Update with your minikube IP
        DOCKER_CERT_PATH = "/var/lib/jenkins/.minikube/certs"
        MINIKUBE_ACTIVE_DOCKERD = "minikube"
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
    }
    stages {
        stage('Set Docker Env to Minikube') {
            steps {
                sh '''
                    eval $(minikube docker-env)
                    echo "[INFO] Docker environment set to Minikube."
                    docker version
                '''
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('Model_Api') {
                    sh '''
                        eval $(minikube docker-env)
                        docker build -t ddd:1.0.0 .
                    '''
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    eval $(minikube docker-env)
                    kubectl apply -f Model_Api/deployment.yaml
                    kubectl apply -f Model_Api/service.yaml
                '''
            }
        }
    }
}
